" Vim Initialization
" " ------------------
set nocompatible
filetype off

" Respect XDG
if isdirectory($XDG_CONFIG_HOME.'/vim')
	let $VIMPATH=expand('$XDG_CONFIG_HOME/vim')
	let $VARPATH=expand('$XDG_CACHE_HOME/vim')
else
	let $VIMPATH=expand('$HOME/.config/nvim')
	let $VARPATH=expand('$HOME/.cache/vim')
endif

function! s:source_file(path)
	execute 'source' fnameescape($VIMPATH.'/config/'.a:path)
endfunction

let g:python_host_prog = expand('$VARPATH/venv/neovim/bin/python')
let g:python3_host_prog = expand('$VARPATH/venv/neovim/bin/python3')

" Vim Directories {{{
" ---------------
if ! isdirectory(expand($VARPATH))
	" Create missing dirs i.e. cache/{undo,backup}
	call mkdir(expand('$VARPATH/undo'), 'p')
	call mkdir(expand('$VARPATH/backup'))
endif

" Ensure custom spelling directory
if ! isdirectory(expand('$VIMPATH/spell'))
	call mkdir(expand('$VIMPATH/spell'))
endif
set undofile swapfile nobackup
set directory=$VARPATH/swap//,$VARPATH,~/tmp,/var/tmp,/tmp
set undodir=$VARPATH/undo//,$VARPATH,~/tmp,/var/tmp,/tmp
set backupdir=$VARPATH/backup/,$VARPATH,~/tmp,/var/tmp,/tmp
set viewdir=$VARPATH/view/
set nospell spellfile=$VIMPATH/spell/en.utf-8.add

""""
let $PROJECT=getcwd()
let $ROOT_MARKER ='.project'
let $PROJECTCONFIG=$PROJECT.'/'.$ROOT_MARKER

""" PLUGINS START """"

" ############ PLUG
let $PLUG=expand('$VIMPATH/plugged')
call plug#begin($PLUG)



" ==========================================
" # Interface
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-commentary'
Plug 'junegunn/vim-easy-align'

Plug 'tpope/vim-sensible'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/vim-asterisk'
Plug 'rhysd/accelerated-jk'
Plug 't9md/vim-quickhl'
Plug 'junegunn/vim-peekaboo'


" for file find and all
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
" tagbar for all the tags
Plug 'majutsushi/tagbar'
" On-demand loading
" Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/nerdtree'
" For Linting
Plug 'neomake/neomake'
" for tmux to move around with hjkl
Plug 'christoomey/vim-tmux-navigator'
" Loading custom VIMrc per project
Plug 'embear/vim-localvimrc'

" ==========================================
" Completion
" Python related
Plug 'vim-python/python-syntax', { 'for': 'python' }
Plug 'Vimjas/vim-python-pep8-indent', { 'for': 'python' }
Plug 'vim-scripts/python_match.vim', { 'for': 'python' }
Plug 'raimon49/requirements.txt.vim', { 'for': 'requirements' }


Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" general syntax completion
Plug 'Shougo/neco-syntax'
" for 'include' and 'file'/include'
Plug 'Shougo/neoinclude.vim'
" C++ completion
Plug 'Shougo/deoplete-clangx'
" GO completion
Plug 'deoplete-plugins/deoplete-go'
" Python Completion
" Plug 'deoplete-plugins/deoplete-jedi'
" for tag completion
Plug 'ludovicchabant/vim-gutentags'
Plug 'deoplete-plugins/deoplete-tag'


" formatting
Plug 'sbdchd/neoformat'

" Snippets
Plug 'SirVer/ultisnips'




" ==========================================
" Odds and Ends
Plug 'mechatroner/rainbow_csv'

Plug 'vimwiki/vimwiki'



call plug#end()

filetype plugin indent on
syntax enable



""" PLUGINS END """"
let g:mapleader="\<Space>"
let g:maplocalleader=';'

" Release keymappings for other purposes
nnoremap <Space>  <Nop>
xnoremap <Space>  <Nop>
nnoremap ;        <Nop>
xnoremap ;        <Nop>


" settings BEFORE loading all the plugins
call s:source_file('general.vim')

call s:source_file('all.vim')

" Loading configuration modules {{{
call s:source_file('filetype.vim')
call s:source_file('utils.vim')
call s:source_file('tabline.vim')
" call s:source_file('completion.vim')
call s:source_file('linting.vim')
call s:source_file('looks.vim')

" source all configurations for plugins
for f in split(glob('$VIMPATH/config/plugins/*.vim'), '\n')
	exe 'source' f
endfor

set termguicolors

" vim: set ts=2 sw=2 tw=80 noet :
