#!/bin/bash

CSCOPE_DIR="$PWD/.project"

if [ ! -d "$CSCOPE_DIR" ]; then
  mkdir "$CSCOPE_DIR"
fi

echo "Finding files ..."
find "$PWD" \
  -name '*.[ch]' \
  -o -name '*.cpp' \
  -o -name '*.cc' \
  -o -name '*.hpp' \
  -o -name '*.py' \
  -o -name '*.vim' > "$CSCOPE_DIR/cscope.files"

echo "Adding files to cscope db: $CSCOPE_DIR/cscope.files ..."
cscope -b -R -q -k -i "$CSCOPE_DIR/cscope.files"

export CSCOPE_DB="$PWD/cscope.out"
echo "Exported CSCOPE_DB to: '$CSCOPE_DB'"
